INSERT INTO `notebook`(`Name`,`IsDefective`,`IsAvailable`)VALUES('HP Pavillion',0,1);
INSERT INTO `notebook`(`Name`,`IsDefective`,`IsAvailable`)VALUES('HP Pavillion',0,1);
INSERT INTO `notebook`(`Name`,`IsDefective`,`IsAvailable`)VALUES('HP Pavillion',0,1);
INSERT INTO `notebook`(`Name`,`IsDefective`,`IsAvailable`)VALUES('HP Pavillion',0,1);
INSERT INTO `notebook`(`Name`,`IsDefective`,`IsAvailable`)VALUES('HP Pavillion',0,1);
INSERT INTO `notebook`(`Name`,`IsDefective`,`IsAvailable`)VALUES('Dell ProBook',0,1);
INSERT INTO `notebook`(`Name`,`IsDefective`,`IsAvailable`)VALUES('Dell ProBood',0,1);
INSERT INTO `notebook`(`Name`,`IsDefective`,`IsAvailable`)VALUES('Dell ProBood',0,1);
INSERT INTO `notebook`(`Name`,`IsDefective`,`IsAvailable`)VALUES('Dell ProBood',0,1);
INSERT INTO `notebook`(`Name`,`IsDefective`,`IsAvailable`)VALUES('Dell ProBood',0,1);
INSERT INTO `notebook`(`Name`,`IsDefective`,`IsAvailable`)VALUES('Sony Vaio',0,1);
INSERT INTO `notebook`(`Name`,`IsDefective`,`IsAvailable`)VALUES('Sony Vaio',0,1);
INSERT INTO `notebook`(`Name`,`IsDefective`,`IsAvailable`)VALUES('Sony Vaio',0,1);
INSERT INTO `notebook`(`Name`,`IsDefective`,`IsAvailable`)VALUES('Sony Vaio',0,1);
INSERT INTO `notebook`(`Name`,`IsDefective`,`IsAvailable`)VALUES('Sony Vaio',0,1);
INSERT INTO `notebook`(`Name`,`IsDefective`,`IsAvailable`)VALUES('One Superbook',0,1);
INSERT INTO `notebook`(`Name`,`IsDefective`,`IsAvailable`)VALUES('One Superbook',0,1);
INSERT INTO `notebook`(`Name`,`IsDefective`,`IsAvailable`)VALUES('One Superbook',0,1);
INSERT INTO `notebook`(`Name`,`IsDefective`,`IsAvailable`)VALUES('One Superbook',0,1);
INSERT INTO `notebook`(`Name`,`IsDefective`,`IsAvailable`)VALUES('One Superbook',0,1);
INSERT INTO `notebook`(`Name`,`IsDefective`,`IsAvailable`)VALUES('Apple MacBook Pro',0,1);
INSERT INTO `notebook`(`Name`,`IsDefective`,`IsAvailable`)VALUES('Apple MacBook Pro',0,1);
INSERT INTO `notebook`(`Name`,`IsDefective`,`IsAvailable`)VALUES('Apple MacBook Pro',0,1);
INSERT INTO `notebook`(`Name`,`IsDefective`,`IsAvailable`)VALUES('Apple MacBook Pro',0,1);
INSERT INTO `notebook`(`Name`,`IsDefective`,`IsAvailable`)VALUES('Apple MacBook Pro',0,1);