/**
 * DetailsPage.java Created by Florian Hauck on 25.03.2013
 */
package com.dhbw_db.view;

import com.dhbw_db.control.MainController;
import com.dhbw_db.model.beans.User;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.PopupDateField;

/**
 * The details layout for one request. Shows buttons to approve or refuse the
 * request if the user is a lecturer. Shows buttons to cancel or extend the
 * request if the user is a student
 * 
 * @author Florian Hauck
 * @version 0.1
 * @since 0.1
 */
@SuppressWarnings("serial")
public class DetailsPage extends CustomComponent {

	@AutoGenerated
	private AbsoluteLayout mainLayout;

	@AutoGenerated
	private HorizontalLayout buttonLayout;

	@AutoGenerated
	private Button extendButton;

	@AutoGenerated
	private PopupDateField extendDateField;

	@AutoGenerated
	private Button cancelButton;

	@AutoGenerated
	private Button refuseButton;

	@AutoGenerated
	private Button approveButton;

	@AutoGenerated
	private Label commentLabel2;

	@AutoGenerated
	private Label commentLabel;

	@AutoGenerated
	private Label statusLabel2;

	@AutoGenerated
	private Label statusLabel;

	@AutoGenerated
	private Label requestEndLabel2;

	@AutoGenerated
	private Label requestEndLabel;

	@AutoGenerated
	private Label endDateLabel2;

	@AutoGenerated
	private Label endDateLabel;

	@AutoGenerated
	private Label startDateLabel2;

	@AutoGenerated
	private Label startDateLabel;

	@AutoGenerated
	private Label creationDateLabel2;

	@AutoGenerated
	private Label createDateLabel;

	@AutoGenerated
	private Label oSLabel2;

	@AutoGenerated
	private Label oSLabel;

	@AutoGenerated
	private Label notebookLabel2;

	@AutoGenerated
	private Label notebookLabel;

	@AutoGenerated
	private Label iDLabel2;

	@AutoGenerated
	private Label iDLabel;

	@AutoGenerated
	private Label headlineLabel;

	private MainController mc;

	/**
	 * The constructor builds the main layout for the view.
	 */
	public DetailsPage() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

	}

	/**
	 * Builds the main layout and adds some labels and the horizontal layout to
	 * it. The horizontal layout contains the buttons.
	 * 
	 * @return The main layout.
	 */
	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");

		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");

		// headlineLabel
		headlineLabel = new Label();
		headlineLabel.setStyleName("headline");
		headlineLabel.setImmediate(false);
		headlineLabel.setWidth("80px");
		headlineLabel.setHeight("-1px");
		headlineLabel.setValue("Details");
		mainLayout.addComponent(headlineLabel, "top:20.0px;left:20.0px;");

		// iDLabel
		iDLabel = new Label();
		iDLabel.setStyleName("subHeadline");
		iDLabel.setImmediate(false);
		iDLabel.setWidth("-1px");
		iDLabel.setHeight("-1px");
		iDLabel.setValue("ID:");
		mainLayout.addComponent(iDLabel, "top:60.0px;left:20.0px;");

		// iDLabel2
		iDLabel2 = new Label();
		iDLabel2.setImmediate(false);
		iDLabel2.setWidth("-1px");
		iDLabel2.setHeight("-1px");
		iDLabel2.setValue("Label");
		mainLayout.addComponent(iDLabel2, "top:60.0px;left:200.0px;");

		// notebookLabel
		notebookLabel = new Label();
		notebookLabel.setStyleName("subHeadline");
		notebookLabel.setImmediate(false);
		notebookLabel.setWidth("-1px");
		notebookLabel.setHeight("-1px");
		notebookLabel.setValue("Notebook:");
		mainLayout.addComponent(notebookLabel, "top:80.0px;left:20.0px;");

		// notebookLabel2
		notebookLabel2 = new Label();
		notebookLabel2.setImmediate(false);
		notebookLabel2.setWidth("-1px");
		notebookLabel2.setHeight("-1px");
		notebookLabel2.setValue("Label");
		mainLayout.addComponent(notebookLabel2, "top:80.0px;left:200.0px;");

		// oSLabel
		oSLabel = new Label();
		oSLabel.setStyleName("subHeadline");
		oSLabel.setImmediate(false);
		oSLabel.setWidth("-1px");
		oSLabel.setHeight("-1px");
		oSLabel.setValue("Betriebssystem:");
		mainLayout.addComponent(oSLabel, "top:100.0px;left:20.0px;");

		// oSLabel2
		oSLabel2 = new Label();
		oSLabel2.setImmediate(false);
		oSLabel2.setWidth("-1px");
		oSLabel2.setHeight("-1px");
		oSLabel2.setValue("Label");
		mainLayout.addComponent(oSLabel2, "top:100.0px;left:200.0px;");

		// createDateLabel
		createDateLabel = new Label();
		createDateLabel.setStyleName("subHeadline");
		createDateLabel.setImmediate(false);
		createDateLabel.setWidth("-1px");
		createDateLabel.setHeight("-1px");
		createDateLabel.setValue("Erstellung des Antrages:");
		mainLayout.addComponent(createDateLabel, "top:120.0px;left:20.0px;");

		// creationDateLabel2
		creationDateLabel2 = new Label();
		creationDateLabel2.setImmediate(false);
		creationDateLabel2.setWidth("-1px");
		creationDateLabel2.setHeight("-1px");
		creationDateLabel2.setValue("Label");
		mainLayout.addComponent(creationDateLabel2, "top:120.0px;left:200.0px;");

		// startDateLabel
		startDateLabel = new Label();
		startDateLabel.setStyleName("subHeadline");
		startDateLabel.setImmediate(false);
		startDateLabel.setWidth("-1px");
		startDateLabel.setHeight("-1px");
		startDateLabel.setValue("Ausleihdatum:");
		mainLayout.addComponent(startDateLabel, "top:140.0px;left:20.0px;");

		// startDateLabel2
		startDateLabel2 = new Label();
		startDateLabel2.setImmediate(false);
		startDateLabel2.setWidth("-1px");
		startDateLabel2.setHeight("-1px");
		startDateLabel2.setValue("Label");
		mainLayout.addComponent(startDateLabel2, "top:140.0px;left:200.0px;");

		// endDateLabel
		endDateLabel = new Label();
		endDateLabel.setStyleName("subHeadline");
		endDateLabel.setImmediate(false);
		endDateLabel.setWidth("-1px");
		endDateLabel.setHeight("-1px");
		endDateLabel.setValue("Rückgabedatum:");
		mainLayout.addComponent(endDateLabel, "top:160.0px;left:20.0px;");

		// endDateLabel2
		endDateLabel2 = new Label();
		endDateLabel2.setImmediate(false);
		endDateLabel2.setWidth("-1px");
		endDateLabel2.setHeight("-1px");
		endDateLabel2.setValue("Label");
		mainLayout.addComponent(endDateLabel2, "top:160.0px;left:200.0px;");

		// requestEndLabel
		requestEndLabel = new Label();
		requestEndLabel.setStyleName("subHeadline");
		requestEndLabel.setImmediate(false);
		requestEndLabel.setWidth("-1px");
		requestEndLabel.setHeight("-1px");
		requestEndLabel.setValue("Ende des Antrages:");
		mainLayout.addComponent(requestEndLabel, "top:180.0px;left:20.0px;");

		// requestEndLabel2
		requestEndLabel2 = new Label();
		requestEndLabel2.setImmediate(false);
		requestEndLabel2.setWidth("-1px");
		requestEndLabel2.setHeight("-1px");
		requestEndLabel2.setValue("Label");
		mainLayout.addComponent(requestEndLabel2, "top:180.0px;left:200.0px;");

		// statusLabel
		statusLabel = new Label();
		statusLabel.setStyleName("subHeadline");
		statusLabel.setImmediate(false);
		statusLabel.setWidth("-1px");
		statusLabel.setHeight("-1px");
		statusLabel.setValue("Status:");
		mainLayout.addComponent(statusLabel, "top:200.0px;left:20.0px;");

		// statusLabel2
		statusLabel2 = new Label();
		statusLabel2.setImmediate(false);
		statusLabel2.setWidth("-1px");
		statusLabel2.setHeight("-1px");
		statusLabel2.setValue("Label");
		mainLayout.addComponent(statusLabel2, "top:200.0px;left:200.0px;");

		// commentLabel
		commentLabel = new Label();
		commentLabel.setStyleName("subHeadline");
		commentLabel.setImmediate(false);
		commentLabel.setWidth("-1px");
		commentLabel.setHeight("-1px");
		commentLabel.setValue("Bemerkung für den Betreuer:");
		mainLayout.addComponent(commentLabel, "top:220.0px;left:20.0px;");

		// commentLabel2
		commentLabel2 = new Label();
		commentLabel2.setImmediate(false);
		commentLabel2.setWidth("-1px");
		commentLabel2.setHeight("-1px");
		commentLabel2.setValue("Label");
		mainLayout.addComponent(commentLabel2, "top:220.0px;left:200.0px;");

		// horizontalLayout_1
		buttonLayout = buildHorizontalLayout_1();
		mainLayout.addComponent(buttonLayout, "top:260.0px;left:18.0px;");

		return mainLayout;
	}

	/**
	 * Builds the horizontal layout and all buttons. Checks if the user is a
	 * student or a lecturer and adds the needed buttons to the layout.
	 * 
	 * @return The horizontal layout which contains the buttons.
	 */
	private HorizontalLayout buildHorizontalLayout_1() {
		// common part: create layout
		buttonLayout = new HorizontalLayout();
		buttonLayout.setImmediate(false);
		buttonLayout.setWidth("-1px");
		buttonLayout.setHeight("-1px");
		buttonLayout.setMargin(false);
		buttonLayout.setSpacing(true);

		// approveButton
		approveButton = new Button();
		approveButton.setCaption("Genehmigen");
		approveButton.setImmediate(true);
		approveButton.setWidth("-1px");
		approveButton.setHeight("-1px");

		// refuseButton
		refuseButton = new Button();
		refuseButton.setCaption("Ablehnen");
		refuseButton.setImmediate(true);
		refuseButton.setWidth("-1px");
		refuseButton.setHeight("-1px");

		// cancelButton
		cancelButton = new Button();
		cancelButton.setCaption("Zurückziehen");
		cancelButton.setImmediate(true);
		cancelButton.setWidth("-1px");
		cancelButton.setHeight("-1px");

		// extendDateField
		extendDateField = new PopupDateField();
		extendDateField.setCaption("Verlängern bis");
		extendDateField.setImmediate(false);
		extendDateField.setWidth("-1px");
		extendDateField.setHeight("23px");

		// extendButton
		extendButton = new Button();
		extendButton.setCaption("Verlängerung");
		extendButton.setImmediate(true);
		extendButton.setWidth("-1px");
		extendButton.setHeight("-1px");

		mc = MainController.get();
		User u = mc.getUser();

		if (u.isStudent()) {
			buttonLayout.addComponent(cancelButton);
			buttonLayout.setComponentAlignment(cancelButton, new Alignment(9));
			buttonLayout.addComponent(extendDateField);
			buttonLayout.addComponent(extendButton);
			buttonLayout.setComponentAlignment(extendButton, new Alignment(9));
		}
		if (u.isLecturer()) {
			buttonLayout.addComponent(approveButton);
			buttonLayout.setComponentAlignment(approveButton, new Alignment(9));
			buttonLayout.addComponent(refuseButton);
			buttonLayout.setComponentAlignment(refuseButton, new Alignment(9));
		}

		return buttonLayout;
	}

}
