/**
 * StudentStartPage.java Created by Florian Hauck on 01.03.2013
 */
package com.dhbw_db.view;

import com.dhbw_db.control.MainController;
import com.dhbw_db.model.beans.User;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.shared.ui.label.ContentMode;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Label;
import com.vaadin.ui.Panel;
import com.vaadin.ui.VerticalLayout;

/**
 * The layout for the start page. Defines all components and their positions.
 * 
 * @author Florian Hauck
 * @version 0.1
 * @since 0.1
 */
public class StartPage extends CustomComponent {

	@AutoGenerated
	private AbsoluteLayout mainLayout;

	@AutoGenerated
	private Panel panel;

	@AutoGenerated
	private AbsoluteLayout panelLayout;

	@AutoGenerated
	private Label studentLabel;

	@AutoGenerated
	private Label HeadlineLabel;

	private static final long serialVersionUID = -5781154539150826766L;

	/**
	 * The constructor should first build the main layout, set the composition
	 * root and then define the table headlines.
	 */
	public StartPage() {
		buildMainLayout();
		setCompositionRoot(mainLayout);
	}

	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");

		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");

		// panel
		panel = buildPanel();
		mainLayout.addComponent(panel, "left:0.0px;");

		return mainLayout;
	}

	@AutoGenerated
	private Panel buildPanel() {
		// common part: create layout
		panel = new Panel();
		panel.setImmediate(false);
		panel.setWidth("100.0%");
		panel.setHeight("100.0%");

		// panelLayout
		panelLayout = buildPanelLayout();
		panel.setContent(panelLayout);

		return panel;
	}

	@AutoGenerated
	private AbsoluteLayout buildPanelLayout() {
		// common part: create layout
		panelLayout = new AbsoluteLayout();
		panelLayout.setImmediate(false);
		panelLayout.setWidth("800px");
		panelLayout.setHeight("500px");

		// HeadlineLabel
		HeadlineLabel = new Label();
		HeadlineLabel.setStyleName("headline");
		HeadlineLabel.setImmediate(false);
		HeadlineLabel.setWidth("-1px");
		HeadlineLabel.setHeight("-1px");
		HeadlineLabel.setValue("Notebookverleih der DHBW Karlsruhe");
		panelLayout.addComponent(HeadlineLabel, "top:39.0px;left:49.0px;");

		VerticalLayout labels = new VerticalLayout();
		labels.setWidth("-1px");
		labels.setHeight("-1px");
		User u = MainController.get()
								.getUser();

		if (u != null && u.isStudent()) {
			// studentLabel
			studentLabel = new Label();
			studentLabel.setImmediate(false);
			studentLabel.setWidth("-1px");
			studentLabel.setHeight("-1px");
			String studentString = "Als Student können Sie:<br>"
					+ "<ul>"
					+ "<li>Neue Anträge anlegen</li>"
					+ "<li>Den Status Ihrer bereits gestellten Anträge verfolgen</li>"
					+ "</ul>";
			studentLabel.setValue(studentString);
			studentLabel.setContentMode(ContentMode.HTML);
			labels.addComponent(studentLabel);
		}
		if (u != null && u.isLecturer()) {
			// studentLabel
			Label lecturerLabel = new Label();
			lecturerLabel.setImmediate(false);
			lecturerLabel.setWidth("-1px");
			lecturerLabel.setHeight("-1px");
			String studentString = "Als Dozent können Sie:<br>"
					+ "<ul>"
					+ "<li>Von Studenten gestellte Anträge freigeben</li>"
					+ "<li>Den Status der Anträge, für die Sie zuständig sind, einsehen</li>"
					+ "</ul>";
			lecturerLabel.setValue(studentString);
			lecturerLabel.setContentMode(ContentMode.HTML);
			labels.addComponent(lecturerLabel);
		}
		if (u != null && u.isAdmin()) {
			// studentLabel
			Label lecturerLabel = new Label();
			lecturerLabel.setImmediate(false);
			lecturerLabel.setWidth("-1px");
			lecturerLabel.setHeight("-1px");
			String studentString = "Als Adminstrator können Sie:<br>"
					+ "<ul>"
					+ "<li>Von Studenten gestellte Anträge einsehe</li>"
					+ "<li>Anträge, die noch nicht beendet sind, abbrechen</li>"
					+ "<li>Anträge ordentlich beenden</li>"
					+ "<li>Notebookstati verändern</li>" + "</ul>";
			lecturerLabel.setValue(studentString);
			lecturerLabel.setContentMode(ContentMode.HTML);
			labels.addComponent(lecturerLabel);
		}

		panelLayout.addComponent(labels, "top:99.0px;left:49.0px;");
		return panelLayout;
	}
}
