/**
 * StudentDetailsPage.java Created by Yannic Frank on 15.03.2013
 */
package com.dhbw_db.view;

import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Button;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.Panel;
import com.vaadin.ui.PopupDateField;
import com.vaadin.ui.Table;
import com.vaadin.ui.VerticalLayout;

/**
 * @author Yannic Frank
 * @version 0.1
 * @since
 */
public class StudentDetailsPage extends CustomComponent {

	private AbsoluteLayout mainLayout;

	private Panel panel;

	private VerticalLayout panelLayout;

	private PopupDateField extendDateField;

	private Button extendButton;

	private Label extendLabel;

	private Button backButton;

	private Button revertButton;

	private Table detailsTable;

	private Label headlineLabel;

	/**
	 * The constructor should first build the main layout, set the composition
	 * root and then do any custom initialization.
	 * 
	 * The constructor will not be automatically regenerated by the visual
	 * editor.
	 */
	public StudentDetailsPage() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		defineTableColumns();
		addTableItems();
	}

	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");

		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");

		// panel_2
		panel = buildPanel();
		mainLayout.addComponent(panel, "top:0.0px;left:0.0px;");

		return mainLayout;
	}

	private Panel buildPanel() {
		// common part: create layout
		panel = new Panel();
		panel.setImmediate(false);
		panel.setWidth("100.0%");
		panel.setHeight("100.0%");

		// panelLayout
		panelLayout = buildpanelLayout();
		panel.setContent(panelLayout);

		return panel;
	}

	private VerticalLayout buildpanelLayout() {
		// common part: create layout
		panelLayout = new VerticalLayout();
		panelLayout.setImmediate(false);
		panelLayout.setSpacing(true);
		panelLayout.setMargin(true);

		// panelLayout.setWidth("100.0%");
		// panelLayout.setHeight("100.0%");

		// headlineLabel
		headlineLabel = new Label();
		headlineLabel.setStyleName("headline");
		headlineLabel.setImmediate(false);
		headlineLabel.setWidth("-1px");
		headlineLabel.setHeight("-1px");
		headlineLabel.setValue("Detailansicht");

		panelLayout.addComponent(headlineLabel);

		// detailTable
		detailsTable = new Table();
		detailsTable.setCaption("Aktueller Leihvorgang (oder Ausgewählter falls wir mehrere gleichzeitig realisieren wollen)");

		detailsTable.setImmediate(false);

		detailsTable.setWidth("100.0%");
		detailsTable.setHeight("45px");

		panelLayout.addComponent(detailsTable);

		// revertButton
		revertButton = new Button();
		revertButton.setCaption("Zurückziehen");
		revertButton.setImmediate(false);
		revertButton.setWidth("-1px");
		revertButton.setHeight("-1px");

		// backButton
		backButton = new Button();
		backButton.setCaption("Abbrechen");
		backButton.setImmediate(false);
		backButton.setWidth("-1px");
		backButton.setHeight("-1px");

		// extendButton
		extendLabel = new Label();
		extendLabel.setImmediate(false);
		extendLabel.setWidth("-1px");
		extendLabel.setHeight("-1px");
		extendLabel.setValue("Verlängern bis:");

		// extendDateField
		extendDateField = new PopupDateField();
		extendDateField.setImmediate(false);
		extendDateField.setWidth("-1px");
		extendDateField.setHeight("-1px");

		// extendButton
		extendButton = new Button();
		extendButton.setCaption("Beantragen");
		extendButton.setImmediate(false);
		extendButton.setWidth("-1px");
		extendButton.setHeight("-1px");

		HorizontalLayout horizontalLayout1 = new HorizontalLayout();

		horizontalLayout1.addComponent(revertButton);
		horizontalLayout1.addComponent(backButton);

		horizontalLayout1.setSpacing(true);

		panelLayout.addComponent(horizontalLayout1);

		HorizontalLayout horizontalLayout2 = new HorizontalLayout();

		horizontalLayout2.addComponent(extendLabel);
		horizontalLayout2.addComponent(extendDateField);
		horizontalLayout2.addComponent(extendButton);

		horizontalLayout2.setSpacing(true);

		panelLayout.addComponent(horizontalLayout2);

		return panelLayout;
	}

	/**
	 * Defines the headlines of the table columns.
	 */
	private void defineTableColumns() {
		detailsTable.addContainerProperty("ID", Integer.class, null);
		detailsTable.addContainerProperty("Notebook", String.class, null);
		detailsTable.addContainerProperty("Betriebssystem", String.class, null);
		detailsTable.addContainerProperty("Betreuer", String.class, null);
		detailsTable.addContainerProperty(	"Erstellung des Antrages",
											String.class,
											null);
		detailsTable.addContainerProperty("Ausleihdatum", String.class, null);
		detailsTable.addContainerProperty("Rückgabedatum", String.class, null);
		detailsTable.addContainerProperty(	"Ende des Antrages",
											String.class,
											null);
		detailsTable.addContainerProperty("Status", String.class, null);
		detailsTable.addContainerProperty(	"Bemerkung für Betreuer",
											String.class,
											null);
	}

	/**
	 * Adds items to the table.
	 */
	private void addTableItems() {
		// TODO Decide in which form this method receives the table items and
		// add
		// these items to the table. Maybe a SQL container might be a good
		// solution.
		// currentRequestTable.setContainerDataSource(container);
	}

}
