/**
 * LecturerOpenRequestsPage.java Created by Yannic Frank on 15.03.2013
 */
package com.dhbw_db.view.lecturer;

import java.util.ArrayList;
import java.util.List;

import com.dhbw_db.control.MainController;
import com.dhbw_db.model.request.Request;
import com.dhbw_db.model.request.Request.Status;
import com.dhbw_db.view.request.RequestTable;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Label;
import com.vaadin.ui.Panel;
import com.vaadin.ui.VerticalLayout;

/**
 * @author Yannic Frank
 * @version 0.1
 * @since
 */
public class LecturerOpenRequestsPage extends CustomComponent {

	private static final long serialVersionUID = 5716916047660854518L;

	private AbsoluteLayout mainLayout;

	private Panel panel;

	private VerticalLayout panelLayout;

	private RequestTable requestsTable;

	private Label headlineLabel;

	/**
	 * The constructor should first build the main layout, set the composition
	 * root and then do any custom initialization.
	 * 
	 * The constructor will not be automatically regenerated by the visual
	 * editor.
	 */
	public LecturerOpenRequestsPage() {
		buildMainLayout();
		setCompositionRoot(mainLayout);
	}

	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");

		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");

		// panel_2
		panel = buildPanel();
		mainLayout.addComponent(panel, "top:0.0px;left:0.0px;");

		return mainLayout;
	}

	private Panel buildPanel() {
		// common part: create layout
		panel = new Panel();
		panel.setImmediate(false);
		panel.setWidth("100.0%");
		panel.setHeight("100.0%");

		// absoluteLayout_3
		panelLayout = buildpanelLayout();
		panel.setContent(panelLayout);

		return panel;
	}

	private VerticalLayout buildpanelLayout() {
		// common part: create layout
		panelLayout = new VerticalLayout();
		panelLayout.setImmediate(false);
		panelLayout.setSpacing(true);
		panelLayout.setMargin(true);
		// panelLayout.setWidth("100.0%");
		// panelLayout.setHeight("100.0%");

		// headlineLabel
		headlineLabel = new Label();
		headlineLabel.setStyleName("headline");
		headlineLabel.setImmediate(false);
		headlineLabel.setWidth("-1px");
		headlineLabel.setHeight("-1px");
		headlineLabel.setValue("Eigene Anträge");
		panelLayout.addComponent(headlineLabel);

		// find open requests
		List<Request> allRequests = MainController.get()
													.getDataAccess()
													.getRequestsForApproverForID(MainController.get()
																								.getUser()
																								.getID());
		List<Request> openRequests = new ArrayList<Request>();

		for (Request rq : allRequests) {
			if (rq.getStatus() == Status.OPEN)
				openRequests.add(rq);
		}
		// detailTable
		requestsTable = new RequestTable(openRequests);
		panelLayout.addComponent(requestsTable);

		return panelLayout;
	}
}
